FROM dpage/pgadmin4:5.1

ENV PGADMIN_DEFAULT_EMAIL=
ENV PGADMIN_DEFAULT_PASSWORD=

ENV PGADMIN_CONFIG_MAIL_SERVER="''"
ENV PGADMIN_CONFIG_MAIL_PORT=
ENV PGADMIN_CONFIG_MAIL_USERNAME="''"
ENV PGADMIN_CONFIG_MAIL_PASSWORD="''"

COPY servers.json /pgadmin4/servers.json

EXPOSE 5050
